var ccb_resources = [
    {type:'ccbi', src:"MainScene.ccbi"},
    {type:'image', src:"gems/2.png"},
    {type:'plist', src:"ccbResources/ccbDefaultImages.plist"},
    {type:'image', src:"ccbResources/ccbParticleSmoke.png"},
    {type:'image', src:"ccbResources/ccbDefaultImages.png"},
    {type:'image', src:"gems/1.png"},
    {type:'image', src:"ccbResources/ccbParticleFire.png"},
    {type:'image', src:"gems/4.png"},
    {type:'image', src:"clickme.png"},
    {type:'image', src:"ccbResources/ccbParticleStars.png"},
    {type:'image', src:"gems/0.png"},
    {type:'ccbi', src:"GameScene.ccbi"},
    {type:'image', src:"gems/3.png"},
    {type:'image', src:"clickme-down.png"},
    {type:'image', src:"ccbResources/ccbParticleSnow.png"},
];
